#!/usr/bin/env ansible-playbook -i localhost,
---
- name: Clone repositories
  hosts: localhost
  connection: local
  
  vars:
    para_areas_path: "{{ ansible_user_dir }}/para/professional/areas"
    directories:
      - "{{ para_areas_path }}"
    repositories:
      - repo: git@github.com:maxcole/home-lab-provider.git
        dest: "{{ para_areas_path }}/home-lab-provider"
      - repo: git@github.com:maxcole/config.git
        dest: "{{ para_areas_path }}/config"
      - repo: git@github.com:maxcole/tools.git
        dest: "{{ para_areas_path }}/tools"
  
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ directories }}"
        
    - name: Clone repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ repositories }}"
